services:
  node:
    image: motion/motion-node-isaac
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
