services:
  node:
    image: nvcr.io/nvidia/isaac-sim:5.0.0
    command:
      - -lc
      - |
        if [ -z "${MOTION}" ]; then
          echo "MOTION not set, exiting";
          exit 0;
        fi
        /isaac-sim/python.sh -m pip install aiohttp nats-py boto3
        sleep infinity
        /isaac-sim/runheadless.sh --enable motion.extension --enable isaacsim.replicator.agent.core  --enable isaacsim.replicator.writers
    profiles: ["gpu"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  storage: {}
