services:
  node:
    command:
      - -lc
      - |
        if [ -z "${MOTION}" ]; then
          echo "MOTION not set, exiting";
          exit 0;
        fi
        apt -y -qq update
        apt -y -qq install curl
        pip install aiohttp nats-py boto3
        python -m server.echo
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:8888/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
